on: [push]
jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
      - run: bundle install
      - run: cp .analysis_variants.yml.example .analysis_variants.yml
      - run: git clone https://github.com/toy/image_optim_analysis.git analysis
      - run: mkdir -p ~/bin
      - run: curl -L "https://www.jonof.id.au/files/kenutils/pngout-20200115-linux.tar.gz" | tar -xz -C ~/bin --strip-components 2 --wildcards '*/amd64/pngout'
      - run: curl -L "https://github.com/shssoichiro/oxipng/releases/download/v4.0.3/oxipng-4.0.3-x86_64-unknown-linux-musl.tar.gz" | tar -xz -C ~/bin --strip-components 1 --wildcards '*oxipng'
      - run: PATH=~/bin:$PATH script/worker_analysis spec/images/**/*.* analysis/**/*.*
      - uses: actions/upload-artifact@v2
        with:
          path: tmp/worker-analysis-*.html
